"""empty message

Revision ID: 2f2c88e7db97
Revises: 
Create Date: 2020-04-21 19:44:36.412124

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2f2c88e7db97'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dashboards_hash_code_key', 'dashboards', type_='unique')
    op.drop_column('dashboards', 'timestamp')
    op.drop_column('dashboards', 'additional_filters')
    op.drop_column('dashboards', 'instances')
    op.drop_column('dashboards', 'properties')
    op.drop_column('dashboards', 'hash_code')
    op.drop_column('dashboards', 'filters')
    op.drop_column('dashboards', 'analysis_filters')
    op.drop_column('dashboards', 'compare_filters')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboards', sa.Column('compare_filters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('dashboards', sa.Column('analysis_filters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('dashboards', sa.Column('filters', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('dashboards', sa.Column('hash_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('dashboards', sa.Column('properties', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('dashboards', sa.Column('instances', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('dashboards', sa.Column('additional_filters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('dashboards', sa.Column('timestamp', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('dashboards_hash_code_key', 'dashboards', ['hash_code'])
    # ### end Alembic commands ###
