"""empty message

Revision ID: 74491be82029
Revises: 270511015a09
Create Date: 2020-04-23 20:56:03.083898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74491be82029'
down_revision = '270511015a09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboards', sa.Column('entity_info', sa.String(), nullable=True))
    op.add_column('dashboards', sa.Column('filters_info', sa.String(), nullable=True))
    op.add_column('dashboards', sa.Column('properties_info', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dashboards', 'properties_info')
    op.drop_column('dashboards', 'filters_info')
    op.drop_column('dashboards', 'entity_info')
    # ### end Alembic commands ###
