"""empty message

Revision ID: 7db3c0000b8a
Revises: b822a9a9365e
Create Date: 2020-05-07 20:26:22.242261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7db3c0000b8a'
down_revision = 'b822a9a9365e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboards', sa.Column('entity_info', sa.JSON(), nullable=True))
    op.add_column('dashboards', sa.Column('filters_info', sa.JSON(), nullable=True))
    op.add_column('dashboards', sa.Column('properties_info', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dashboards', 'properties_info')
    op.drop_column('dashboards', 'filters_info')
    op.drop_column('dashboards', 'entity_info')
    # ### end Alembic commands ###
