"""empty message

Revision ID: 9d1511171d66
Revises: 7ff333189482
Create Date: 2020-04-18 18:38:16.288982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d1511171d66'
down_revision = '7ff333189482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('entity', sa.String(), nullable=True),
    sa.Column('hash_code', sa.String(), nullable=True),
    sa.Column('filters', sa.String(), nullable=True),
    sa.Column('properties', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dashboards')
    # ### end Alembic commands ###
