"""empty message

Revision ID: b822a9a9365e
Revises: 74491be82029
Create Date: 2020-05-07 17:20:50.550605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b822a9a9365e'
down_revision = '74491be82029'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dashboards', 'filters_info')
    op.drop_column('dashboards', 'entity_info')
    op.drop_column('dashboards', 'properties_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboards', sa.Column('properties_info', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('dashboards', sa.Column('entity_info', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('dashboards', sa.Column('filters_info', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
