"""empty message

Revision ID: f99b2b0a80ce
Revises: 
Create Date: 2020-05-08 20:07:57.835794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f99b2b0a80ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('entity', sa.String(), nullable=True),
    sa.Column('hash_code', sa.String(), nullable=True),
    sa.Column('filters', sa.String(), nullable=True),
    sa.Column('properties', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('instances', sa.JSON(), nullable=True),
    sa.Column('compare_filters', sa.String(), nullable=True),
    sa.Column('analysis_filters', sa.String(), nullable=True),
    sa.Column('additional_filters', sa.String(), nullable=True),
    sa.Column('entity_info', sa.JSON(), nullable=True),
    sa.Column('filters_info', sa.JSON(), nullable=True),
    sa.Column('properties_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dashboards')
    # ### end Alembic commands ###
